import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectFipaBundle,fetchFipaBundle} from '../lib/fipa-collector.ts';
const rows=[['1205','2026년 친환경양식 기술 교육 바이오플락 초급과정 교육생 공모','2026.09.04'],['1204','[공모기간 연장] 2026년 친환경양식 기술 교육 아쿠아포닉스 고급과정 교육생 공모(연장)','2026.09.02'],...Array.from({length:8},(_,i)=>[String(1203-i),`2026년 친환경양식 기술소개 일정 및 사전등록 안내 ${i}`,'2026.08.01'])];
const list=()=>rows.map(([id,title,date],i)=>`<div class="board_box"><strong>${81-i}</strong><a href="./detail.do?ntt_sn=${id}">${title}</a><li><span>등록일 : </span>${date}</li></div>`).join('')+'<div class="pagination">';
const detail=(id:string,title:string,date:string,period:string)=>`<div class="view_tit"><strong>${title}</strong><li><span>등록일 : </span>${date}</li></div><div class="view_con">교육생 모집 ○ 모집기간: ${period} 접수기간 외 신청서는 선발대상에서 제외됩니다.</div><a href="./down.do?bbs_id=2002&amp;atfile_sn=1&amp;data_ty_cd=A&amp;ntt_sn=${id}">다운로드</a>`;
const bundle=()=>JSON.stringify({list:list(),details:rows.slice(0,2).map(([id,title,date],i)=>({id,html:detail(id,title,date,i?'2026. 8. 10.(월) ~ 9. 30.(수) 16:00까지':'2026. 9. 1.(화) ~ 9. 18.(금) 16:00까지')}))});
test('FIPA preserves exact cutoff, institution and candidate-only eligibility',()=>{const r=collectFipaBundle(bundle(),[],new Date('2026-09-05'));assert.equal(r.items.length,2);assert.equal(r.items[0].institution,'한국어촌어항공단');assert.equal(r.items[0].status,'open');assert.equal(r.items[0].applicationTo,'2026-09-18');assert.equal(r.items[0].closesAt?.toISOString(),'2026-09-18T07:00:00.000Z');assert.match(r.items[0].audience,/첨부 공고문 확인/);});
test('FIPA omits newly found closed rounds but tracks known IDs',()=>{assert.equal(collectFipaBundle(bundle(),[],new Date('2026-10-01')).items.length,0);const r=collectFipaBundle(bundle(),['1205'],new Date('2026-10-01'));assert.equal(r.items.length,1);assert.equal(r.items[0].status,'closed');});
test('FIPA rejects identity, attachment and duplicate drift without partial results',()=>{assert.throws(()=>collectFipaBundle(bundle().replace('ntt_sn=1205','ntt_sn=9999')));assert.throws(()=>collectFipaBundle(bundle().replace('bbs_id=2002','bbs_id=9')));assert.throws(()=>collectFipaBundle(bundle().replace('"id":"1204"','"id":"1205"')));});
test('FIPA rejects impossible dates and cutoff times',()=>{assert.throws(()=>collectFipaBundle(bundle().replace('9. 18.(금) 16:00','2. 30.(금) 16:00')));assert.throws(()=>collectFipaBundle(bundle().replace('9. 18.(금) 16:00','9. 18.(금) 25:00')));});
test('FIPA fixed list and derived official details reject redirects',async()=>{const calls:string[]=[];const mock=(async u=>{calls.push(String(u));if(calls.length===1)return new Response(list()+' '.repeat(25_000));const row=rows[calls.length-2];return new Response(detail(row[0],row[1],row[2],'2026. 9. 1.(화) ~ 9. 18.(금) 16:00까지')+' '.repeat(25_000));}) as typeof fetch;await fetchFipaBundle(mock);assert.equal(calls.length,3);assert.equal(calls[0],'https://fipa.or.kr/eco/bbs/i-278/list.do');assert.match(calls[1],/detail\.do\?ntt_sn=1205$/);});
