import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKidpBundle,fetchKidpBundle} from '../lib/kidp-collector.ts';
const pdfUrl='https://www.kidp.or.kr/usr/upload/board/zboardcommon333/20260904094101150_5038.0.pdf';
const html=`<form id="frontBoardVo"><h3 class="Ttitle">디자인전문기업 금융지원 희망기업 25차 모집 공고</h3><a href="?bbsno=19225">본문</a><a href="${pdfUrl}">PDF</a> 한국디자인진흥원 공고 제2026–98호 2026-09-04 2026-09-17 디자인전문기업 및 활용기업 20개사 내외 designfinance@kidp.or.kr</form>`;
const bundle=(value=html)=>JSON.stringify({html:value,pdfBytes:456304,pdfMagic:'%PDF-1.4',pdfEnd:'%%EOF\n',pdfHash:'741b824690241949ce9834901bd42c5aff18295428cd9ab2b1572f592ca2ebb8'});
test('KIDP emits one repayable finance opportunity without inventing a budget',()=>{const r=collectKidpBundle(bundle(),[],new Date('2026-09-16T12:00:00+09:00'));assert.equal(r.items.length,1);assert.equal(r.items[0].externalId,'19225');assert.match(r.items[0].category,/상환 필요/);assert.equal(r.items[0].supportBudget,null);assert.equal(r.items[0].closesAt,null);assert.equal(r.items[0].status,'open');});
test('KIDP keeps a date-only deadline unknown on the deadline day then closed',()=>{assert.equal(collectKidpBundle(bundle(),[],new Date('2026-09-17T12:00:00+09:00')).items[0].status,'unknown');assert.equal(collectKidpBundle(bundle(),['19225'],new Date('2026-09-18T00:00:00+09:00')).items[0].status,'closed');assert.equal(collectKidpBundle(bundle(),[],new Date('2026-09-18T00:00:00+09:00')).items.length,0);});
test('KIDP fails closed on identity, evidence, or PDF drift',()=>{assert.throws(()=>collectKidpBundle(bundle(html.replace('20개사 내외','30개사 내외'))));assert.throws(()=>collectKidpBundle(bundle().replace('741b8246','841b8246')));assert.throws(()=>collectKidpBundle(bundle().replace('19225','19224')));});
test('KIDP fetch audits fixed detail and PDF without redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const bytes=new Uint8Array(456304);bytes.set(new TextEncoder().encode('%PDF-1.4'));bytes.set(new TextEncoder().encode('%%EOF\n'),bytes.length-6);const mock=(async(u,i)=>{calls.push([String(u),i]);return calls.length===1?new Response(html+' '.repeat(41_000)):new Response(bytes);}) as typeof fetch;const fetched=await fetchKidpBundle(mock);assert.throws(()=>collectKidpBundle(fetched),/구조 확인/);assert.equal(calls.length,2);for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
