import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKimstPage,fetchKimstPage,collectKimstOpportunity,fetchKimstOpportunity} from '../lib/kimst-collector.ts';
const page=()=>`<h3>연구시설 공동활용 사업</h3> 연구시설 사용 건당 최대 천만원 이내에서 사용료 지원 중소중견기업 : 사용료의 75% 대학연구소 단체 : 사용료의 80% 학생 및 신진연구자 : 사용료의 100% (상시)시설이용 신청 접수 및 확인(KIMST) 지원금 초과비용 또는 지원비용 외 사용료는 신청자가 부담`;
test('KIMST imports the standing facility-fee support without inventing a total budget',()=>{const i=collectKimstPage(page()).items[0];assert.equal(i.externalId,'research-facility-standing');assert.equal(i.status,'open');assert.equal(i.closesAt,null);assert.equal(i.supportBudget,null);assert.match(i.applicationMethod,/1천만원/);});
test('KIMST preserves the three beneficiary rates',()=>{const i=collectKimstPage(page()).items[0];assert.match(i.audience,/중소·중견기업/);assert.match(i.applicationMethod,/75%/);assert.match(i.applicationMethod,/80%/);assert.match(i.applicationMethod,/100%/);});
test('KIMST closes only a known standing call after an explicit scoped stop notice',()=>{const h=page()+' 시설이용 신청 접수 종료';assert.equal(collectKimstPage(h).items.length,0);assert.equal(collectKimstPage(h,['research-facility-standing']).items[0].status,'closed');assert.equal(collectKimstPage(page()+' 다른 교육 신청 접수 종료').items[0].status,'open');});
test('KIMST rejects missing or comment-only evidence and redirects',async()=>{assert.throws(()=>collectKimstPage(page().replace('75%','70%')));assert.throws(()=>collectKimstPage(`<!-- ${page()} -->`));const mock=(async()=>new Response('',{status:302,headers:{location:'https://example.com'}})) as typeof fetch;await assert.rejects(()=>fetchKimstPage(mock));});
const oceanPage=()=>`<h3>2026 예비오션스타 기업 모집 공고</h3> 해양수산부 공고 제2026-1276호 작성일 2026-08-24 문의 02-3460-0376 <a href="/fileDown.do?fn=filename_202608240449451506">[공고] 2026년 예비오션스타 모집 공고문.hwp</a> https://badabom.go.kr/stup/pbanc/detail/view.do?pbancMngNo=S-ANN202600020`;
const estuaryMirror=()=>`IRIS2026033279 2026년도 연안하구 인간-자연시스템 관리기술 개발 사업 신규과제 선정계획 재공고 공고 상세 정보의 경우 IRIS 정보를 참조해 주세요`;
const estuaryIris=()=>`2026-09-02 00:00:00 ~ 2026-09-09 16:00:00 해양수산부 공고 제2026-1283호 전문기관 해양수산과학기술진흥원 2026년도 연안하구 인간-자연시스템 관리기술 개발 사업 신규과제 선정계획 재공고.hwpx`;
const ocean=()=>JSON.stringify({html:oceanPage(),fileBytes:76288,fileHash:'9fb3cca0f929d6a2bd3d8d0513006d0cdab4e007705d83bb4d87b82183922a64',mirrorHtml:estuaryMirror(),irisHtml:estuaryIris(),estuaryBytes:134364,estuaryHash:'76bac4ddc605ae9db85e7362af7ff1ff845efe744f81af4532db3c44ccb121d8'});
test('KIMST imports one canonical Ocean Star card with exact eligibility and deadline',()=>{const i=collectKimstOpportunity(ocean(),[],new Date('2026-09-06T00:00:00+09:00')).items[0];assert.equal(i.externalId,'S-ANN202600020');assert.equal(i.status,'open');assert.equal(i.closesAt.toISOString(),'2026-09-11T08:00:00.000Z');assert.equal(i.supportBudget,null);assert.match(i.audience,/100억원/);assert.match(i.applicationMethod,/금융 연계/);assert.match(i.applicationMethod,/S-ANN202600020/);assert.match(i.sourceUrl,/kimst/);});
test('KIMST Ocean Star omits a newly expired card but closes an existing card',()=>{const after=new Date('2026-09-12T00:00:00+09:00');assert.equal(collectKimstOpportunity(ocean(),[],after).items.length,0);assert.equal(collectKimstOpportunity(ocean(),['S-ANN202600020'],after).items[0].status,'closed');});
test('KIMST Ocean Star rejects partial, comment-only, or changed attachment evidence',()=>{assert.throws(()=>collectKimstOpportunity(ocean().replace('S-ANN202600020','S-ANN202600021')));assert.throws(()=>collectKimstOpportunity(JSON.stringify({html:`<!-- ${oceanPage()} -->`,fileBytes:76288,fileHash:'9fb3cca0f929d6a2bd3d8d0513006d0cdab4e007705d83bb4d87b82183922a64'})));assert.throws(()=>collectKimstOpportunity(ocean().replace('9fb3cca0','0fb3cca0')));});
test('KIMST Ocean Star fetch rejects a redirect in either official artifact',async()=>{let n=0;const mock=(async()=>{n++;return n===1?new Response('x'.repeat(180000),{status:200}):new Response('',{status:302});}) as typeof fetch;await assert.rejects(()=>fetchKimstOpportunity(mock));});
test('KIMST enriches the existing MOF IRIS record instead of creating a duplicate',()=>{const i=collectKimstOpportunity(ocean(),[],new Date('2026-09-06T00:00:00+09:00')).items.find(x=>x.externalId==='68185');assert.equal(i.sourceId,'mof-board');assert.equal(i.institution,'해양수산부');assert.equal(i.status,'open');assert.equal(i.closesAt.toISOString(),'2026-09-09T07:00:00.000Z');assert.equal(i.supportBudget,15000000000);assert.match(i.audience,/산·학·연 컨소시엄/);assert.match(i.applicationMethod,/제출 버튼/);});
test('KIMST keeps a known closed IRIS round and rejects mirror, IRIS, or HWPX drift',()=>{const after=new Date('2026-09-10T00:00:00+09:00');assert.equal(collectKimstOpportunity(ocean(),[],after).items.some(x=>x.externalId==='68185'),false);assert.equal(collectKimstOpportunity(ocean(),['68185'],after).items.find(x=>x.externalId==='68185').status,'closed');assert.throws(()=>collectKimstOpportunity(ocean().replace('2026-1283','2026-1284')));assert.throws(()=>collectKimstOpportunity(ocean().replace('76bac4dd','06bac4dd')));});
