import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKofpiBundle,fetchKofpiBundle} from '../lib/kofpi-collector.ts';
const ex=[['12609','[모집] 산양삼 등 산촌자원 활용 시제품 개발 지원 참여자 모집(연중 상시 모집)','2026-08-24'],['12611','2026년 한국임업진흥원 Ⅹ 마르쉐 「먹거리 숲」 참가기업 모집 연장 공고(~9.11)','2026-08-27']] as const;
const list=()=>[...ex,...Array.from({length:8},(_,i)=>[String(12000+i),`채용 결과 ${i}`,'2026-08-01'] as const)].map(([id,title,date],i)=>`<tr><td>${3030-i}</td><td class="title"><a href="#" onclick="fnGoView('${id}'); return false;"><span class="badge badge-notice">공지</span>${title}</a><div>조회</div></td><td>1</td><td>${date}</td></tr>`).join('');
const detail=(i:number)=>`<tr class="title"><h3>${ex[i][1]}</h3><strong>작성일</strong> ${ex[i][2]}</tr><td colspan="4" class="view_cont">${i===0?'한국임업진흥원 공고 제2026-50호 임업인 및 기업 5개사 내외 1개사 당 8백만원 이내 전문가 자문 한국임업진흥원이 직접 집행 2026. 8. 24.(월) ~ 12. 31.(금) 예산 소진 시 접수가 조기 마감 전자우편 또는 방문·우편 접수':'임산물 오프라인 판로 확보 사업자등록이 완료된 자 판매 및 전시공간 셋팅 지원 18개사 내외 2026. 8. 27.(목) ~ 2026. 9. 11 .(금 ), 18:00까지 전자우편으로 제출서류 접수'}</td>`;
const bundle=()=>JSON.stringify({list:list(),details:ex.map((x,i)=>({id:x[0],html:detail(i)}))});
test('KOFPI separates budget-exhaustion support from exact-time market call',()=>{const r=collectKofpiBundle(bundle(),[],new Date('2026-09-05'));assert.equal(r.items.length,2);assert.equal(r.items[0].status,'unknown');assert.equal(r.items[0].closesAt,null);assert.equal(r.items[0].supportBudget,8_000_000);assert.equal(r.items[1].status,'open');assert.equal(r.items[1].closesAt?.toISOString(),'2026-09-11T09:00:00.000Z');});
test('KOFPI does not confuse display number with stable bb_seq',()=>{const r=collectKofpiBundle(bundle());assert.deepEqual(r.items.map(x=>x.externalId),['12609','12611']);assert.match(r.items[0].sourceUrl,/bb_seq=12609$/);});
test('KOFPI omits new ended calls but tracks known closure',()=>{const now=new Date('2027-01-02');assert.equal(collectKofpiBundle(bundle(),[],now).items.length,0);const r=collectKofpiBundle(bundle(),['12609','12611'],now);assert.deepEqual(r.items.map(x=>x.status),['closed','closed']);});
test('KOFPI rejects list, identity and core fact drift',()=>{assert.throws(()=>collectKofpiBundle(bundle().replace("fnGoView('12609')","fnGoView('99999')")));assert.throws(()=>collectKofpiBundle(bundle().replace('8백만원','9백만원')));assert.throws(()=>collectKofpiBundle(bundle().replace('"id":"12611"','"id":"12609"')));});
test('KOFPI uses fixed official requests without redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const mock=(async(u,i)=>{calls.push([String(u),i]);return new Response((calls.length===1?list():detail(calls.length-2))+' '.repeat(45_000));}) as typeof fetch;await fetchKofpiBundle(mock);assert.equal(calls.length,3);assert.equal(calls[0][0],'https://www.kofpi.or.kr/notice/notice_01.do');for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
