import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKoicaBundle,fetchKoicaBundle} from '../lib/koica-collector.ts';
const title='📢 2026년 국제개발협력 청년 공모전 개최!(~9/30)';
const list=()=>Array.from({length:10},(_,i)=>`<a onclick="fnDetail('${i?60+i:'48'}')">${i?`일반 공지 ${i}`:title}</a><p class="date">2026-09-02</p>`).join('');
const detail=()=>`<input value="https://www.worldfriendskorea.or.kr/kor/info/noticeDetail.do?noticeNo=48"><p class="tit">${title}</p><li>2026-09-02</li><div>청년의 경험과 아이디어 청년들의 KOICA 사업 참여 청년들의 참여 강화 방안 2026. 8. 27. ~ 9. 30. 18:00 A4 10페이지 이내 PDF 파일로 제출 대상: 150만 원 상당 외교부장관상 KOICA 이사장상 공모전 홈페이지 https://mofa2.spectory.net/mofa2</div>`;
const bundle=()=>JSON.stringify({list:list(),detail:detail()});
test('KOICA youth contest preserves verified eligibility, method and exact cutoff',()=>{const r=collectKoicaBundle(bundle(),[],new Date('2026-09-05'));assert.equal(r.items.length,1);assert.equal(r.items[0].externalId,'48');assert.equal(r.items[0].status,'open');assert.equal(r.items[0].closesAt.toISOString(),'2026-09-30T09:00:00.000Z');assert.match(r.items[0].applicationMethod,/PDF/);});
test('KOICA omits a newly expired contest but tracks known closure',()=>{const now=new Date('2026-10-01');assert.equal(collectKoicaBundle(bundle(),[],now).items.length,0);assert.equal(collectKoicaBundle(bundle(),['48'],now).items[0].status,'closed');});
test('KOICA rejects identity, date and evidence drift',()=>{assert.throws(()=>collectKoicaBundle(bundle().replace("fnDetail('48')","fnDetail('49')")));assert.throws(()=>collectKoicaBundle(bundle().replace('2026. 8. 27.','2026. 8. 28.')));assert.throws(()=>collectKoicaBundle(bundle().replace('150만 원','160만 원')));assert.throws(()=>collectKoicaBundle(bundle().replace('noticeNo=48','noticeNo=49')));});
test('KOICA uses only fixed public list and detail without redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const mock=(async(u,i)=>{calls.push([String(u),i]);return new Response((calls.length===1?list():detail())+' '.repeat(40_000));}) as typeof fetch;await fetchKoicaBundle(mock);assert.deepEqual(calls.map(x=>x[0]),['https://www.worldfriendskorea.or.kr/kor/info/noticeList.do','https://www.worldfriendskorea.or.kr/kor/info/noticeDetail.do?noticeNo=48']);for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
