import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKoipaBundle,fetchKoipaBundle} from '../lib/koipa-collector.ts';
const html='<a href="?noticeSeq=58"></a><a href="/ipcenter/downloadNoticeAttatch.do?fileSeq=488"></a> 글로벌 온라인 플랫폼 진출(희망) 기업을 위한 해외 권리확보 지원사업 26-M00020 2026-09-01 13:00 2026-09-15 17:00 중소/중견기업';
const bundle=(h=html)=>JSON.stringify({html:h,pdfBytes:405506,pdfMagic:'%PDF-1.6',pdfEnd:'0\r\n%%EOF',pdfHash:'f8c4acf1c1cea7825d6ce1c222582244d04535710d5c17719b86d2de525e94a8'});
test('KOIPA imports one exact-time beneficiary opportunity',()=>{const r=collectKoipaBundle(bundle(),[],new Date('2026-09-06T12:00:00+09:00'));assert.equal(r.items.length,1);assert.equal(r.items[0].externalId,'58');assert.equal(r.items[0].status,'open');assert.equal(r.items[0].closesAt.toISOString(),'2026-09-15T08:00:00.000Z');assert.equal(r.items[0].supportBudget,null);});
test('KOIPA tracks known closure but does not import a newly expired round',()=>{assert.equal(collectKoipaBundle(bundle(),['58'],new Date('2026-09-15T17:00:01+09:00')).items[0].status,'closed');assert.equal(collectKoipaBundle(bundle(),[],new Date('2026-09-15T17:00:01+09:00')).items.length,0);});
test('KOIPA fails closed on identity, time, or PDF drift',()=>{assert.throws(()=>collectKoipaBundle(bundle(html.replace('26-M00020','26-M00021'))));assert.throws(()=>collectKoipaBundle(bundle().replace('17:00','18:00')));assert.throws(()=>collectKoipaBundle(bundle().replace('f8c4acf1','a8c4acf1')));});
test('KOIPA fetch uses only fixed no-redirect detail and PDF',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const bytes=new Uint8Array(405506);bytes.set(new TextEncoder().encode('%PDF-1.6'));bytes.set(new TextEncoder().encode('0\r\n%%EOF'),bytes.length-8);const mock=(async(u,i)=>{calls.push([String(u),i]);return calls.length===1?new Response(html+' 한'.repeat(10_000)):new Response(bytes);}) as typeof fetch;const result=await fetchKoipaBundle(mock);assert.throws(()=>collectKoipaBundle(result));assert.equal(calls.length,2);for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
