import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKoregBundle,fetchKoregBundle} from '../lib/koreg-collector.ts';
const titles=['2026년 소상공인(개인사업자) 비즈플러스카드 지원사업 시행 공고','2026년 소상공인(법인사업자) 비즈플러스카드 지원사업 시행 공고','2026년 관광진흥개발기금 신용보증부 운영자금 특별융자 지원 지침 공고'];
const page=(i:number)=>`<h2>${titles[i]}</h2><span class="s_title">소관부처·지자체</span><div class="txt">${i===2?'문화체육관광부':'중소벤처기업부'}</div><span class="s_title">사업수행기관</span><div class="txt">신용보증재단중앙회</div><span class="s_title">신청기간</span><div class="txt">${i===2?'2026.01.02 ~ 2026.11.13':'예산 소진시까지'}</div><span class="s_title">사업개요</span><div class="txt">${i===0?'개인사업자':i===1?'법인사업자':'관광진흥법상 관광사업'} 소상공인 카드한도 소상공인당 최대 1,000만원 ${i===2?'최대 2억원 특별융자 3년 거치 3년 분할상환':''}</div><span class="s_title">사업신청 방법</span><div class="txt">${i===2?'관할 지역신용보증재단 영업점 방문 신청':'지역신용보증재단에 보증신청 후 IBK기업은행에 카드 발급신청'}</div>`;
const bundle=(pages=[0,1,2].map(page))=>JSON.stringify({pages});
test('KOREG long-lived opportunities preserve issuer, performer and finance type',()=>{const r=collectKoregBundle(bundle(),[],new Date('2026-09-05'));assert.equal(r.items.length,3);assert.equal(r.items[0].sourceId,'bizinfo');assert.equal(r.items[0].institution,'신용보증재단중앙회');assert.equal(r.items[0].ministry,'중소벤처기업부');assert.equal(r.items[0].status,'unknown');assert.equal(r.items[2].category,'융자·금융지원(상환 필요)');assert.equal(r.items[2].closesAt,null);});
test('KOREG does not merge personal and corporate calls or invent budget-exhaustion dates',()=>{const r=collectKoregBundle(bundle()).items;assert.notEqual(r[0].externalId,r[1].externalId);assert.equal(r[0].applicationTo,null);assert.match(r[0].deadlineLabel,/접수 가능 여부 확인/);});
test('KOREG fails the bundle on issuer, performer, identity or method drift',()=>{for(const pages of [[0,1,2].map(page).map((x,i)=>i===0?x.replace('중소벤처기업부','금융위원회'):x),[0,1,2].map(page).map((x,i)=>i===1?x.replace('신용보증재단중앙회','다른 기관'):x),[0,1,2].map(page).map((x,i)=>i===2?x.replace('방문 신청','온라인 신청'):x)])assert.throws(()=>collectKoregBundle(bundle(pages)));});
test('KOREG fixed detail requests reject redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const mock=(async(u,i)=>{calls.push([String(u),i]);return new Response(page(calls.length-1)+' '.repeat(60_000));}) as typeof fetch;await fetchKoregBundle(mock);assert.equal(calls.length,3);for(const [u,i] of calls){assert.match(u,/^https:\/\/www\.bizinfo\.go\.kr\/sii\/siia\/selectSIIA200Detail\.do\?pblancId=PBLN_[0-9]+$/);assert.equal(i?.redirect,'manual');}});
test('KOREG rejects an upstream redirect response',async()=>{const mock=(async()=>new Response('',{status:302,headers:{location:'https://example.com'}})) as typeof fetch;await assert.rejects(()=>fetchKoregBundle(mock),/HTTP 302/);});
test('KOREG dated call is unknown on its date-only deadline',()=>{assert.equal(collectKoregBundle(bundle(),[],new Date('2026-11-12T14:59:59Z')).items[2].status,'open');assert.equal(collectKoregBundle(bundle(),[],new Date('2026-11-12T15:00:00Z')).items[2].status,'unknown');});
test('KOREG finished dated call is only retained when already known',()=>{const now=new Date('2026-12-01');assert.equal(collectKoregBundle(bundle(),[],now).items.length,2);assert.equal(collectKoregBundle(bundle(),['PBLN_000000000117127'],now).items.length,3);});
