import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node tests use explicit extensions.
import {collectKoreahanaBundle,fetchKoreahanaBundle} from '../lib/koreahana-collector.ts';
const rows=[['20469','2026년도 하반기 남북하나재단 장학생 선발 공고(~9.21)','2026-09-04'],['20465','2026년 창업디딤돌센터 9월 (예비)창업가 창업교육 참여자 모집공고(~9.18)','2026-09-01'],['20339','북향민 탈수급 촉진 지원사업 대상자 모집 공고(예산 소진 시까지)','2026-07-13'],['20102','2026년 북향민 청년 ‘미래날개’ 응시료 지원 사업 신청자 모집 공고(~12.5)','2026-04-16']];
const list=()=>rows.concat(Array.from({length:11},(_,i)=>[String(20500+i),`일반 ${i}`,'2026-09-05'])).map(x=>`<tr><a onclick="fn_edit('detail', '${x[0]}', 'N')">${x[1]}</a> ${x[2]}</tr>`).join('');
const details=[`${rows[0][1]} 북한이탈주민지원재단 공고 제2026–98호 접수기간 : 9. 4 ~ 9. 21. 18:00 재단 온라인 신청시스템 장학금 지원 우편접수 불가 부모 명의 신청불가`,`${rows[1][1]} 북한이탈주민지원재단 공고 제2026-97호 창업에 관심이 있는 북향민 20명 이내 대중교통비 지원 2026년 9월 18일 17시까지 didim@nkrf.or.kr 방문 또는 우편접수`,`${rows[2][1]} 제2026-82호 기초생활수급자 및 차상위계층 공고일로부터 ~ 정원충족시까지 조기마감 일체험 50만원`,`${rows[3][1]} 제2026-44호 만19세~만39세 북향민 청년 30명 내외 공고일~12월 5일 예산소진 시 조기 종료 1인 최대 2종, 15만원까지 지원 Lsmean@nkrf.or.kr`];
const bundle=()=>JSON.stringify({list:list(),details:rows.map((x,i)=>({id:x[0],html:details[i]}))});
test('Koreahana keeps four direct opportunities and conservative rolling status',()=>{const r=collectKoreahanaBundle(bundle(),[],new Date('2026-09-05'));assert.equal(r.items.length,4);assert.equal(r.items[0].closesAt!.toISOString(),'2026-09-21T09:00:00.000Z');assert.equal(r.items[1].closesAt!.toISOString(),'2026-09-18T08:00:00.000Z');assert.equal(r.items[2].status,'unknown');assert.equal(r.items[2].closesAt,null);assert.equal(r.items[3].supportBudget,null);assert.equal(r.items[3].closesAt,null);});
test('Koreahana omits newly expired dated rounds, tracks known closure and retains rolling support',()=>{const fresh=collectKoreahanaBundle(bundle(),[],new Date('2026-10-01')).items;assert.deepEqual(fresh.map(x=>x.externalId),['20339','20102']);assert.equal(collectKoreahanaBundle(bundle(),['20469'],new Date('2026-10-01')).items[0].status,'closed');});
test('Koreahana rejects identity, evidence and duplicate detail drift',()=>{assert.throws(()=>collectKoreahanaBundle(bundle().replace('20469','20468')));assert.throws(()=>collectKoreahanaBundle(bundle().replace('18:00','19:00')));assert.throws(()=>collectKoreahanaBundle(bundle().replace('20명 이내','30명 이내')));});
test('Koreahana fetches only fixed public pages without redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const bodies=[list(),...details];const mock=(async(u,i)=>{calls.push([String(u),i]);return new Response(bodies[calls.length-1]+' '.repeat(160_000));}) as typeof fetch;await fetchKoreahanaBundle(mock);assert.equal(calls.length,5);for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
