import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node test runner uses explicit extensions.
import {collectSemasBundle,fetchSemasBundle,semasSource} from '../lib/semas-collector.ts';
const title='2026년 9월 일시적경영애로자금(직접대출) 신청안내';
const row=(id=402,name=title)=>({bltwtrTitNm:name,rnum:1,bltwtrClcd:'대출정보',bltwtrSeq:id,bbsTypeCd:'01',loanSeCdNm:'직접대출',bbsFxnYn:'Y',frstRegDt:'2026-09-04'});
const list=(first:Record<string,unknown>=row())=>JSON.stringify({result:[first,...Array.from({length:9},(_,i)=>({...row(500+i,'과거 안내'),frstRegDt:'2026-08-01'}))],pagination:{pageNo:'1',pageSize:10,totalCount:74}});
const detail=(body='연매출 1억 4백만원 미만 업력 7년 미만 2026년 9월 7일 (월) 10:00 ~ 예산 소진 시까지 대출금 조기회수')=>`<p class="view_title">${title}</p><a onclick="fnDownFile(1)">PDF</a><a onclick="fnDownFile(2)">HWP</a><div id="cntnDiv">${body}</div><script>function fnDownFile(bltwtrFlSeq){$('#bltwtrSeq').val('402');$('#bbsTypeCd').val('01');}</script>`;
const bundle=(l=list(),d=detail())=>JSON.stringify({list:l,detail:d});
test('SEMAS preserves loan type and budget-exhaustion semantics',()=>{const item=collectSemasBundle(bundle(),[],new Date('2026-09-05')) .items[0];assert.equal(item.category,'융자·금융지원(상환 필요)');assert.equal(item.status,'upcoming');assert.equal(item.applicationFrom,'2026-09-07');assert.equal(item.applicationTo,null);assert.equal(item.closesAt,null);assert.match(item.deadlineLabel,/예산 소진/);});
test('SEMAS becomes unknown after opening, never fabricating a close date',()=>{const item=collectSemasBundle(bundle(),[],new Date('2026-09-08')).items[0];assert.equal(item.status,'unknown');assert.equal(item.closesAt,null);});
test('SEMAS validates list identity, detail facts and attachment relationship',()=>{for(const b of [bundle(list(row(402,'다른 공고'))),bundle(list(),detail('연매출 1억 4백만원 미만')),JSON.stringify({list:'login',detail:detail()}),bundle(JSON.stringify({result:[row()],pagination:{pageNo:'1',pageSize:10,totalCount:1}}))])assert.throws(()=>collectSemasBundle(b));});
test('SEMAS fixed requests share bounded evidence paths',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const mock=(async(url,init)=>{calls.push([String(url),init]);return new Response(calls.length===1?list():detail(),{status:calls.length===1?201:200});}) as typeof fetch;await fetchSemasBundle(mock);assert.equal(calls[0][0],semasSource.url);assert.equal(calls[0][1]?.method,'POST');assert.ok(String(calls[0][1]?.body).includes('pageNo=1'));assert.equal(calls[1][0],'https://ols.semas.or.kr/ols/man/SMAN052M/page.do?bltwtrSeq=402&bbsTypeCd=01');for(const [,init] of calls)assert.equal(init?.redirect,'manual');});
test('SEMAS does not admit the 2026 round as new after its operating year',()=>{assert.equal(collectSemasBundle(bundle(),[],new Date('2027-01-02')).items.length,0);assert.equal(collectSemasBundle(bundle(),['402'],new Date('2027-01-02')).items.length,1);});
