import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Native Node test runner uses explicit extensions.
import {collectSmtechBundle,fetchSmtechBundle,smtechSource} from '../lib/smtech-collector.ts';
const title='2026년 제6차 중소기업 R&D 전담은행 투자지원 추천기업(방산 및 전략기술) 모집 공고';
const row=(i:number,t='지원사업 공고')=>`<tr><td>SMTECH</td><td>사업</td><td><a href="/front/ifg/no/notice02_detail.do;jsessionid=temp.node?ancmId=S${String(2877+i).padStart(5,'0')}&amp;buclCd=S9171&amp;dtlAncmSn=1&amp;aplySn=1&amp;pageIndex=1" class="board">${t}</a></td><td>2026. 09. 03 ~ 2026. 09. 28</td><td>2026-09-03</td></tr>`;
const list=()=>`<table><th>시스템구분</th><th>접수기간</th><th>공고일</th>${Array.from({length:15},(_,i)=>row(i,i?undefined:title)).join('')}</table>`;
const detail=()=>`<table><tr><th>제목</th><td>${title}</td></tr><tr><th>사업명</th><td>전담은행 투자설명회(IR)</td></tr><tr><th>시행기관</th><td>중소기업기술정보진흥원</td></tr><tr><th>시작일자</th><td>2026-09-03</td></tr><tr><th>종료일자</th><td>2026-09-28</td></tr></table><p>중소기업 R&D 수행기업 12대 국가전략기술</p><a href="javascript:cfn_AtchFileDownload('EC1A1CEE2A787A200CE45338FD3959C5','/front','fileDownFrame');">모집안내</a><a>전담은행 투자지원프로그램 FAQ.hwp</a>`;
const bundle=(l=list(),d=detail())=>JSON.stringify({list:l,detail:d});
test('SMTECH keeps issuer, composite identity and date-only deadline',()=>{const i=collectSmtechBundle(bundle(),[],new Date('2026-09-05')).items[0];assert.equal(i.externalId,'S02877:S9171:1:1');assert.equal(i.institution,'중소기업기술정보진흥원');assert.equal(i.applicationTo,'2026-09-28');assert.equal(i.closesAt,null);assert.match(i.deadlineLabel,/마감시각 원문 확인/);});
test('SMTECH rejects row, issuer and attachment drift without partial candidates',()=>{for(const b of [bundle(list().replace('S02877','S99999')),bundle(list(),detail().replace('중소기업기술정보진흥원','국가과학기술연구회')),bundle(list(),detail().replace('EC1A1CEE2A787A200CE45338FD3959C5','bad'))])assert.throws(()=>collectSmtechBundle(b));});
test('SMTECH fixed requests cannot follow session redirects',async()=>{const calls:Array<[string,RequestInit|undefined]>=[];const mock=(async(u,i)=>{calls.push([String(u),i]);return new Response((calls.length===1?list():detail())+' '.repeat(60_000));}) as typeof fetch;await fetchSmtechBundle(mock);assert.equal(calls[0][0],smtechSource.url);assert.match(calls[1][0],/ancmId=S02877/);for(const [,i] of calls)assert.equal(i?.redirect,'manual');});
test('SMTECH does not import a finished round as new',()=>{assert.equal(collectSmtechBundle(bundle(),[],new Date('2026-10-01')).items.length,0);assert.equal(collectSmtechBundle(bundle(),['S02877:S9171:1:1'],new Date('2026-10-01')).items.length,1);});
