export const kiboSource={id:'kibo-opportunities',institutionId:'public-294',name:'기술보증기금 기업지원·공공조달 추천',url:'https://tb.kibo.or.kr/kbsmna/application/bsmna/bsConsFndApplicationBoard.do?article.offset=0&mode=list'};
const urls={foundation:kiboSource.url,overall:'https://tb.kibo.or.kr/kbsmna/application/bsmna/bsConsOvrApplicationBoard.do?article.offset=0&mode=list',info:'https://tb.kibo.or.kr/kbsmna/application/bsmna/bsConsInfo.do',venture:'https://www.kibo.or.kr/vc/grnt/grnt09/vnNara.do'};
function invalid():never{throw new Error('기술보증기금 지원사업 구조 확인 필요');}
function plain(value:string){return value.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):parseInt(n,10))).replace(/&nbsp;|&ensp;|&emsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/&middot;/gi,'·').replace(/\s+/g,' ').trim();}
async function read(fetcher:typeof fetch,url:string,signal:AbortSignal){const response=await fetcher(url,{redirect:'manual',signal,headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'}});if(!response.ok)throw new Error(`KIBO opportunities HTTP ${response.status}`);const body=await response.text();if(body.length<30_000||body.length>400_000)invalid();return body;}
export async function fetchKiboBundle(fetcher:typeof fetch=fetch){const signal=AbortSignal.timeout(20_000);const [foundation,overall,info,venture]=await Promise.all(Object.values(urls).map(url=>read(fetcher,url,signal)));return JSON.stringify({foundation,overall,info,venture});}
export function collectKiboBundle(input:string){let data:Record<string,unknown>;try{data=JSON.parse(input);}catch{invalid();}for(const key of Object.keys(urls))if(typeof data[key]!=='string')invalid();
  const foundation=plain(data.foundation as string),overall=plain(data.overall as string),info=plain(data.info as string),venture=plain(data.venture as string),rawFoundation=data.foundation as string,rawOverall=data.overall as string;
  const common=['총 게시물 1 건','기업승계 M&A 활성화를 위한 2026년도 컨설팅 지원사업 시행계획 공고','2026-08-01 ~ 2026-12-31','2026-08-04','공모중'];for(const fact of common)if(!foundation.includes(fact)||!overall.includes(fact))invalid();if(!rawFoundation.includes('articleNo=1898')||!rawOverall.includes('articleNo=1901'))invalid();
  for(const fact of ['기초컨설팅','종합컨설팅','100개사','70만원','40개사','700만원','예산 소진'])if(!info.includes(fact))invalid();
  for(const fact of ['상시모집','매달 20일','매달 말일','벤처기업','창업 7년 이내','기술평가등급 BB등급 이상','디지털지점'])if(!venture.includes(fact))invalid();
  return {parsedPages:4,items:[
    {sourceId:kiboSource.id,externalId:'mna-consulting-2026',institution:'기술보증기금',group:'공사·공단',title:'2026년도 기업승계 M&A 컨설팅 지원사업',category:'경영·사업승계 컨설팅',audience:'기업승계를 위한 매도 희망 중소기업 또는 인수 희망 개인·법인 · 트랙별 세부요건 확인',region:null,sourceName:kiboSource.name,sourceUrl:urls.info,announcedFrom:'2026-08-04',applicationFrom:'2026-04-01',applicationTo:'2026-12-31',opensAt:new Date('2026-04-01T00:00:00+09:00'),closesAt:null,deadlineLabel:'예산 소진 시까지 · 시스템상 2026-12-31',status:'unknown',ministry:'중소벤처기업부',supportBudget:null,applicationMethod:'기업승계 M&A 매칭시스템에서 기초 또는 종합컨설팅 온라인 신청'},
    {sourceId:kiboSource.id,externalId:'venture-nara-2026',institution:'기술보증기금',group:'공사·공단',title:'2026년 벤처나라 상품등록 추천',category:'판로·공공조달 지원',audience:'기보 거래기업 중 벤처기업 또는 창업 7년 이내 기업 · 완제품·기술평가 등 세부요건 충족 필요',region:null,sourceName:kiboSource.name,sourceUrl:urls.venture,announcedFrom:null,applicationFrom:'2026-01-01',applicationTo:'2026-12-20',opensAt:new Date('2026-01-01T00:00:00+09:00'),closesAt:null,deadlineLabel:'상시 모집 · 매월 20일 회차 마감',status:'unknown',ministry:'중소벤처기업부',supportBudget:null,applicationMethod:'기술보증기금 디지털지점 신청 후 추천받은 기업이 조달청에 별도 신청'}
  ]};
}
