export const kimstSource={id:'kimst-research-facility',institutionId:'public-325',name:'해양수산과학기술진흥원 연구시설 공동활용',url:'https://www.kimst.re.kr/u/rnd/joint_project_02/content.do'};
export const kimstOpportunitySource={id:'kimst-opportunities',institutionId:'public-325',name:'해양수산과학기술진흥원 기업지원 공고',url:'https://www.kimst.re.kr/u/news/notice_01/board.do?bno=153421765145800&type=view'};
function invalid():never{throw new Error('해양수산과학기술진흥원 연구시설 공동활용 구조 확인 필요');}
function plain(v:string){return v.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#8596;/g,'↔').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
export async function fetchKimstPage(fetcher:typeof fetch=fetch){const r=await fetcher(kimstSource.url,{headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'},redirect:'manual',signal:AbortSignal.timeout(20_000)});if(!r.ok)throw new Error(`KIMST research facility HTTP ${r.status}`);const h=await r.text(),n=new TextEncoder().encode(h).length;if(n<150_000||n>260_000)invalid();return h;}
export function collectKimstPage(html:string,knownIds:string[]=[]){const p=plain(html),id='research-facility-standing';for(const fact of ['연구시설 공동활용 사업','연구시설 사용 건당 최대 천만원 이내에서 사용료 지원','중소중견기업 : 사용료의 75%','대학연구소 단체 : 사용료의 80%','학생 및 신진연구자 : 사용료의 100%','(상시)시설이용 신청 접수 및 확인(KIMST)','지원금 초과비용 또는 지원비용 외 사용료는 신청자가 부담'])if(!p.includes(fact))invalid();const closed=p.includes('시설이용 신청 접수 종료')||p.includes('연구시설 공동활용 사업 종료');if(closed&&!knownIds.includes(id))return {parsedPages:1,items:[]};return {parsedPages:1,items:[{sourceId:kimstSource.id,externalId:id,institution:'해양수산과학기술진흥원',group:'공사·공단',title:'해양수산 연구시설 공동활용 사용료 지원',category:'연구시설·장비 사용료 지원',audience:'중소·중견기업, 대학·연구소·단체, 학생 및 신진연구자',region:'전국',sourceName:kimstSource.name,sourceUrl:kimstSource.url,announcedFrom:null,applicationFrom:null,applicationTo:null,opensAt:null,closesAt:null,deadlineLabel:closed?'공식 페이지 접수 종료':'상시 접수',status:closed?'closed':'open',ministry:'해양수산부',supportBudget:null,applicationMethod:'바다봄 공동활용 서비스에서 시설을 찾고 보유기관과 일정을 협의한 뒤 신청 · 건당 최대 1천만원 이내에서 기업 75%, 대학·연구소·단체 80%, 학생·신진연구자 100% 사용료 지원'}]};}

const oceanAttachment='https://www.kimst.re.kr/fileDown.do?fn=filename_202608240449451506&dn=%5b%ea%b3%b5%ea%b3%a0%5d+2026%eb%85%84+%ec%98%88%eb%b9%84%ec%98%a4%ec%85%98%ec%8a%a4%ed%83%80+%eb%aa%a8%ec%a7%91+%ea%b3%b5%ea%b3%a0%eb%ac%b8.hwp';
const oceanHash='9fb3cca0f929d6a2bd3d8d0513006d0cdab4e007705d83bb4d87b82183922a64';
const estuaryMirror='https://www.kimst.re.kr/u/rnd/inform_01/pjtAnuc.do?anucno=IRIS2026033279&type=view';
const estuaryIris='https://www.iris.go.kr/contents/retrieveBsnsAncmView.do?ancmId=023757&bsnsAncmSn=2&bsnsYyDetail=2026&chngRcveDeFro=2026%2F09%2F02&chngRcveDeTo=2026%2F09%2F09&sorgnBsnsCd=S051028';
const estuaryAttachment='https://www.iris.go.kr/comm/file/fileDownload.do?atchDocId=HrRMYh18DXFRhbOzQzR3KQ%3D%3D&atchFileId=crSHzPxqVqLW%2B9uq9U4EFw%3D%3D';
const estuaryHash='76bac4ddc605ae9db85e7362af7ff1ff845efe744f81af4532db3c44ccb121d8';
async function digest(bytes:ArrayBuffer){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
export async function fetchKimstOpportunity(fetcher:typeof fetch=fetch){const headers={'user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'},request=(url:string,accept:string)=>fetcher(url,{headers:{...headers,accept},redirect:'manual',signal:AbortSignal.timeout(20_000)});const [page,file,mirror,iris,estuaryFile]=await Promise.all([request(kimstOpportunitySource.url,'text/html'),request(oceanAttachment,'application/octet-stream'),request(estuaryMirror,'text/html'),request(estuaryIris,'text/html'),request(estuaryAttachment,'application/octet-stream')]);if(!page.ok||!file.ok||!mirror.ok||!iris.ok||!estuaryFile.ok)throw new Error(`KIMST opportunity HTTP ${page.status}/${file.status}/${mirror.status}/${iris.status}/${estuaryFile.status}`);const html=await page.text(),bytes=await file.arrayBuffer(),mirrorHtml=await mirror.text(),irisHtml=await iris.text(),estuaryBytes=await estuaryFile.arrayBuffer(),n=new TextEncoder().encode(html).length,b=new Uint8Array(bytes),eb=new Uint8Array(estuaryBytes);if(n<170_000||n>260_000||b.byteLength!==76288||!b.slice(0,8).every((v,i)=>v===[208,207,17,224,161,177,26,225][i])||mirrorHtml.length<150_000||irisHtml.length<50_000||eb.byteLength!==134364||!eb.slice(0,4).every((v,i)=>v===[80,75,3,4][i]))throw new Error('해양수산과학기술진흥원 기업·R&D 공고 구조 확인 필요');return JSON.stringify({html,fileBytes:b.byteLength,fileHash:await digest(bytes),mirrorHtml,irisHtml,estuaryBytes:eb.byteLength,estuaryHash:await digest(estuaryBytes)});}
export function collectKimstOpportunity(input:string,knownIds:string[]=[],now=new Date()){
  let bundle:{html?:unknown;fileBytes?:unknown;fileHash?:unknown;mirrorHtml?:unknown;irisHtml?:unknown;estuaryBytes?:unknown;estuaryHash?:unknown};try{bundle=JSON.parse(input);}catch{throw new Error('해양수산과학기술진흥원 기업·R&D 공고 구조 확인 필요');}
  if(typeof bundle.html!=='string'||bundle.fileBytes!==76288||bundle.fileHash!==oceanHash||typeof bundle.mirrorHtml!=='string'||typeof bundle.irisHtml!=='string'||bundle.estuaryBytes!==134364||bundle.estuaryHash!==estuaryHash)throw new Error('해양수산과학기술진흥원 기업·R&D 공고 구조 확인 필요');
  const html=bundle.html;
  const clean=html.replace(/<!--[\s\S]*?-->/g,' '),p=plain(clean),id='S-ANN202600020';
  for(const fact of ['2026 예비오션스타 기업 모집 공고','해양수산부 공고 제2026-1276호','2026-08-24','02-3460-0376','[공고] 2026년 예비오션스타 모집 공고문.hwp','filename_202608240449451506','S-ANN202600020'])if(!p.includes(fact)&&!clean.includes(fact))throw new Error('해양수산과학기술진흥원 예비오션스타 구조 확인 필요');
  const start=new Date('2026-08-20T00:00:00+09:00'),end=new Date('2026-09-11T17:00:00+09:00');
  const items:any[]=[];
  if(now<=end||knownIds.includes(id))items.push({sourceId:kimstOpportunitySource.id,externalId:id,institution:'해양수산과학기술진흥원',group:'공사·공단',title:'2026 예비오션스타 기업 모집',category:'해양수산 유망기업 성장지원',audience:'최근 3년 평균매출 100억원 이상이며 성장성이 기대되는 해양수산 기업 · 창업 3년 이내는 창업 이후 평균 적용 · 5개사 이내 선정',region:'전국',sourceName:kimstOpportunitySource.name,sourceUrl:kimstOpportunitySource.url,announcedFrom:'2026-08-20',applicationFrom:'2026-08-20',applicationTo:'2026-09-11',opensAt:start,closesAt:end,deadlineLabel:'2026-09-11 17:00까지',status:now<start?'upcoming':now>end?'closed':'open',ministry:'해양수산부',supportBudget:null,applicationMethod:'바다봄 신청페이지(S-ANN202600020)에서 회원가입 후 온라인 신청 · 선정기업에 홍보, 금융 연계, R&D·사업화 참여 우대, 투자유치 및 인력양성 지원'});
  const mirrorText=plain(bundle.mirrorHtml),irisText=plain(bundle.irisHtml),estuaryId='IRIS2026033279';
  for(const fact of ['IRIS2026033279','2026년도 연안하구 인간-자연시스템 관리기술 개발 사업 신규과제 선정계획 재공고','공고 상세 정보의 경우 IRIS 정보를 참조해 주세요'])if(!mirrorText.includes(fact))throw new Error('해양수산과학기술진흥원 연안하구 R&D 구조 확인 필요');
  for(const fact of ['2026-09-02 00:00:00 ~ 2026-09-09 16:00:00','해양수산부 공고 제2026-1283호','전문기관 해양수산과학기술진흥원','2026년도 연안하구 인간-자연시스템 관리기술 개발 사업 신규과제 선정계획 재공고.hwpx'])if(!irisText.includes(fact))throw new Error('IRIS 연안하구 R&D 구조 확인 필요');
  const estuaryStart=new Date('2026-09-02T00:00:00+09:00'),estuaryEnd=new Date('2026-09-09T16:00:00+09:00');
  if(now<=estuaryEnd||knownIds.includes(estuaryId))items.push({sourceId:kimstOpportunitySource.id,externalId:estuaryId,institution:'해양수산과학기술진흥원',group:'공사·공단',title:'2026년도 연안하구 인간-자연시스템 관리기술 개발 신규과제 재공고',category:'해양환경 연구개발(R&D)',audience:'국가·지자체 연구기관, 대학, 출연연, 기업·중소기업, 비영리법인, 공공기관 등 연구개발기관 · 별도 법인의 산·학·연 컨소시엄 구성 필수',region:'전국',sourceName:kimstOpportunitySource.name,sourceUrl:estuaryIris,announcedFrom:'2026-08-26',applicationFrom:'2026-09-02',applicationTo:'2026-09-09',opensAt:estuaryStart,closesAt:estuaryEnd,deadlineLabel:'2026-09-09 16:00까지',status:now<estuaryStart?'upcoming':now>estuaryEnd?'closed':'open',ministry:'해양수산부',supportBudget:15000000000,applicationMethod:'IRIS에서 연구개발계획서를 작성·저장한 뒤 마감 전 최종확인하고 제출 버튼까지 완료 · 기업 참여 시 연구개발비 일부 부담 · 1개 과제, 총 5년 이내·2026년 정부지원연구개발비 19억원 이내'});
  return {parsedPages:5,items};
}
