export const kimstSource={id:'kimst-research-facility',institutionId:'public-325',name:'해양수산과학기술진흥원 연구시설 공동활용',url:'https://www.kimst.re.kr/u/rnd/joint_project_02/content.do'};
export const kimstOpportunitySource={id:'kimst-opportunities',institutionId:'public-325',name:'해양수산과학기술진흥원 기업지원 공고',url:'https://www.kimst.re.kr/u/news/notice_01/board.do?bno=153421765145800&type=view'};
function invalid():never{throw new Error('해양수산과학기술진흥원 연구시설 공동활용 구조 확인 필요');}
function plain(v:string){return v.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#8596;/g,'↔').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();}
export async function fetchKimstPage(fetcher:typeof fetch=fetch){const r=await fetcher(kimstSource.url,{headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'},redirect:'manual',signal:AbortSignal.timeout(20_000)});if(!r.ok)throw new Error(`KIMST research facility HTTP ${r.status}`);const h=await r.text(),n=new TextEncoder().encode(h).length;if(n<150_000||n>260_000)invalid();return h;}
export function collectKimstPage(html:string,knownIds:string[]=[]){const p=plain(html),id='research-facility-standing';for(const fact of ['연구시설 공동활용 사업','연구시설 사용 건당 최대 천만원 이내에서 사용료 지원','중소중견기업 : 사용료의 75%','대학연구소 단체 : 사용료의 80%','학생 및 신진연구자 : 사용료의 100%','(상시)시설이용 신청 접수 및 확인(KIMST)','지원금 초과비용 또는 지원비용 외 사용료는 신청자가 부담'])if(!p.includes(fact))invalid();const closed=p.includes('시설이용 신청 접수 종료')||p.includes('연구시설 공동활용 사업 종료');if(closed&&!knownIds.includes(id))return {parsedPages:1,items:[]};return {parsedPages:1,items:[{sourceId:kimstSource.id,externalId:id,institution:'해양수산과학기술진흥원',group:'공사·공단',title:'해양수산 연구시설 공동활용 사용료 지원',category:'연구시설·장비 사용료 지원',audience:'중소·중견기업, 대학·연구소·단체, 학생 및 신진연구자',region:'전국',sourceName:kimstSource.name,sourceUrl:kimstSource.url,announcedFrom:null,applicationFrom:null,applicationTo:null,opensAt:null,closesAt:null,deadlineLabel:closed?'공식 페이지 접수 종료':'상시 접수',status:closed?'closed':'open',ministry:'해양수산부',supportBudget:null,applicationMethod:'바다봄 공동활용 서비스에서 시설을 찾고 보유기관과 일정을 협의한 뒤 신청 · 건당 최대 1천만원 이내에서 기업 75%, 대학·연구소·단체 80%, 학생·신진연구자 100% 사용료 지원'}]};}

const oceanAttachment='https://www.kimst.re.kr/fileDown.do?fn=filename_202608240449451506&dn=%5b%ea%b3%b5%ea%b3%a0%5d+2026%eb%85%84+%ec%98%88%eb%b9%84%ec%98%a4%ec%85%98%ec%8a%a4%ed%83%80+%eb%aa%a8%ec%a7%91+%ea%b3%b5%ea%b3%a0%eb%ac%b8.hwp';
const oceanHash='9fb3cca0f929d6a2bd3d8d0513006d0cdab4e007705d83bb4d87b82183922a64';
async function digest(bytes:ArrayBuffer){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
export async function fetchKimstOpportunity(fetcher:typeof fetch=fetch){const [page,file]=await Promise.all([fetcher(kimstOpportunitySource.url,{headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'},redirect:'manual',signal:AbortSignal.timeout(20_000)}),fetcher(oceanAttachment,{headers:{accept:'application/octet-stream','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'},redirect:'manual',signal:AbortSignal.timeout(20_000)})]);if(!page.ok||!file.ok)throw new Error(`KIMST opportunity HTTP ${page.status}/${file.status}`);const html=await page.text(),bytes=await file.arrayBuffer(),n=new TextEncoder().encode(html).length,b=new Uint8Array(bytes);if(n<170_000||n>260_000||b.byteLength!==76288||!b.slice(0,8).every((v,i)=>v===[208,207,17,224,161,177,26,225][i]))throw new Error('해양수산과학기술진흥원 예비오션스타 구조 확인 필요');return JSON.stringify({html,fileBytes:b.byteLength,fileHash:await digest(bytes)});}
export function collectKimstOpportunity(input:string,knownIds:string[]=[],now=new Date()){
  let bundle:{html?:unknown;fileBytes?:unknown;fileHash?:unknown};try{bundle=JSON.parse(input);}catch{throw new Error('해양수산과학기술진흥원 예비오션스타 구조 확인 필요');}
  if(typeof bundle.html!=='string'||bundle.fileBytes!==76288||bundle.fileHash!==oceanHash)throw new Error('해양수산과학기술진흥원 예비오션스타 구조 확인 필요');
  const html=bundle.html;
  const clean=html.replace(/<!--[\s\S]*?-->/g,' '),p=plain(clean),id='S-ANN202600020';
  for(const fact of ['2026 예비오션스타 기업 모집 공고','해양수산부 공고 제2026-1276호','2026-08-24','02-3460-0376','[공고] 2026년 예비오션스타 모집 공고문.hwp','filename_202608240449451506','S-ANN202600020'])if(!p.includes(fact)&&!clean.includes(fact))throw new Error('해양수산과학기술진흥원 예비오션스타 구조 확인 필요');
  const start=new Date('2026-08-20T00:00:00+09:00'),end=new Date('2026-09-11T17:00:00+09:00');
  if(now>end&&!knownIds.includes(id))return {parsedPages:1,items:[]};
  return {parsedPages:2,items:[{sourceId:kimstOpportunitySource.id,externalId:id,institution:'해양수산과학기술진흥원',group:'공사·공단',title:'2026 예비오션스타 기업 모집',category:'해양수산 유망기업 성장지원',audience:'최근 3년 평균매출 100억원 이상이며 성장성이 기대되는 해양수산 기업 · 창업 3년 이내는 창업 이후 평균 적용 · 5개사 이내 선정',region:'전국',sourceName:kimstOpportunitySource.name,sourceUrl:kimstOpportunitySource.url,announcedFrom:'2026-08-20',applicationFrom:'2026-08-20',applicationTo:'2026-09-11',opensAt:start,closesAt:end,deadlineLabel:'2026-09-11 17:00까지',status:now<start?'upcoming':now>end?'closed':'open',ministry:'해양수산부',supportBudget:null,applicationMethod:'바다봄 신청페이지(S-ANN202600020)에서 회원가입 후 온라인 신청 · 선정기업에 홍보, 금융 연계, R&D·사업화 참여 우대, 투자유치 및 인력양성 지원'}]};
}
