export const kistaSource={id:'kista-opportunities',institutionId:'public-310',name:'한국특허전략개발원 지원기관 사업공고',url:'https://biz.kista.re.kr/ippro/com/iprndMain/selectBusinessAnnounceList.do?bbsType=bs&pageIndex=1'};
const detailUrl='https://biz.kista.re.kr/ippro/com/iprndMain/selectBusinessAnnounceView.do?bbsType=bs&DepthCode1=2&DepthCode2=1&annId=864&annYy=2026';
const filePath='/iprnd_data/RND-IP2_DATA/BSANNC/FILE_000000001285373';
const fileName='[붙임1] 참여기업 과제 등록 공고.pdf';
const fileUrl=()=>{const u=new URL('https://biz.kista.re.kr/ippro/dext5upload/handler/dext5handler.jsp');u.searchParams.set('dext5CMD','downloadRequest');u.searchParams.set('resumeMode','0');u.searchParams.set('fileVirtualPath',filePath);u.searchParams.set('fileOrgName',fileName);return u.toString();};
const title='[과제공고] 산업기술 R&D 연계 IP 솔루션 지원사업 과제 등록 공고(자유공모)';
const expectedHash='9d2c067f3f515e5eb2cfa12b8b5a3a8a0a0d41c5933a1e08ea36982e8fb2387c';
function invalid():never{throw new Error('한국특허전략개발원 지원기관 사업공고 구조 확인 필요');}
function plain(v:string){return v.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();}
async function sha(b:ArrayBuffer){const d=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('');}
export async function fetchKistaBundle(fetcher:typeof fetch=fetch){const headers={accept:'text/html,application/pdf','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'};const [lr,dr,pr]=await Promise.all([fetcher(kistaSource.url,{headers,redirect:'manual',signal:AbortSignal.timeout(20_000)}),fetcher(detailUrl,{headers,redirect:'manual',signal:AbortSignal.timeout(20_000)}),fetcher(fileUrl(),{headers,redirect:'manual',signal:AbortSignal.timeout(20_000)})]);if(!lr.ok||!dr.ok||!pr.ok)throw new Error(`KISTA opportunities HTTP ${lr.status}/${dr.status}/${pr.status}`);const list=await lr.text(),detail=await dr.text(),b=await pr.arrayBuffer(),v=new Uint8Array(b),lb=new TextEncoder().encode(list).length,db=new TextEncoder().encode(detail).length;if(lb<50_000||lb>120_000||db<45_000||db>100_000||v.length<300_000||v.length>500_000)invalid();return JSON.stringify({list,detail,pdfBytes:v.length,pdfMagic:new TextDecoder().decode(v.slice(0,8)),pdfEnd:new TextDecoder().decode(v.slice(-8)),pdfHash:await sha(b)});}
export function collectKistaBundle(input:string,knownIds:string[]=[],now=new Date()){let d:Record<string,unknown>;try{d=JSON.parse(input);}catch{invalid();}if(typeof d.list!=='string'||typeof d.detail!=='string'||d.pdfBytes!==399980||d.pdfMagic!=='%PDF-1.6'||d.pdfEnd!=='5\r\n%%EOF'||d.pdfHash!==expectedHash)invalid();const detail=plain(d.detail),row=d.list.match(/<tr>[\s\S]*?view\('2026','864'\)[\s\S]*?<\/tr>/)?.[0];if(!row||!plain(row).includes(title)||!row.includes('접수중')||!d.list.includes('총건수'))invalid();for(const fact of [title,'2026-08-25 09시 00분','2026-11-30 11시 00분','FILE_000000001285373','399980',fileName])if(!detail.includes(fact)&&!d.detail.includes(fact))invalid();if(!d.detail.includes('name="annId" value="864"')||!d.detail.includes('name="annYy" value="2026"'))invalid();const id='2026-864',start=Date.parse('2026-08-25T09:00:00+09:00'),end=Date.parse('2026-11-30T11:00:00+09:00');if(now.getTime()>=end&&!knownIds.includes(id))return {parsedPages:3,items:[]};return {parsedPages:3,items:[{sourceId:kistaSource.id,externalId:id,institution:'한국특허전략개발원',group:'공사·공단',title:'산업기술 R&D 연계 IP 솔루션 지원사업 과제 등록(자유공모)',category:'기업 R&D·특허전략 지원',audience:'정부 R&D 협약기업 중 중소벤처기업부 소관 R&D를 제외한 참여기업 · 세부 과제 적합성은 공고문 확인',region:null,sourceName:kistaSource.name,sourceUrl:detailUrl,announcedFrom:'2026-08-25',applicationFrom:'2026-08-25',applicationTo:'2026-11-30',opensAt:new Date('2026-08-25T09:00:00+09:00'),closesAt:new Date('2026-11-30T11:00:00+09:00'),deadlineLabel:'2026-11-30 11:00까지',status:now.getTime()<start?'upcoming':now.getTime()>=end?'closed':'open',ministry:'지식재산처',supportBudget:null,applicationMethod:'IP통합지원포털에서 기관계정으로 과제 등록 · 기업부담금과 세부 제출서류는 공식 공고문 확인'}]};}
