export const kofpiSource={id:'kofpi-support',institutionId:'public-234',name:'한국임업진흥원 임업인·기업 지원',url:'https://www.kofpi.or.kr/notice/notice_01.do'};
const base='https://www.kofpi.or.kr/notice/notice_01view.do?bb_seq=';
type KofpiItem={sourceId:string;externalId:string;institution:string;group:string;title:string;category:string;audience:string;region:string|null;sourceName:string;sourceUrl:string;announcedFrom:string;applicationFrom:string|null;applicationTo:string|null;opensAt:Date|null;closesAt:Date|null;deadlineLabel:string;status:string;ministry:string;supportBudget?:number|null;applicationMethod:string};
const expected=[
  {id:'12609',title:'[모집] 산양삼 등 산촌자원 활용 시제품 개발 지원 참여자 모집(연중 상시 모집)',posted:'2026-08-24'},
  {id:'12611',title:'2026년 한국임업진흥원 Ⅹ 마르쉐 「먹거리 숲」 참가기업 모집 연장 공고(~9.11)',posted:'2026-08-27'},
] as const;
function invalid():never{throw new Error('한국임업진흥원 지원사업 구조 확인 필요');}
function plain(value:string){return value.replace(/<!--[^]*?-->/g,' ').replace(/<script\b[^>]*>[^]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
async function read(fetcher:typeof fetch,url:string,signal:AbortSignal){const response=await fetcher(url,{redirect:'manual',signal,headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'}});if(!response.ok)throw new Error(`KOFPI ${new URL(url).searchParams.get('bb_seq')||'list'} HTTP ${response.status}`);const body=await response.text();if(body.length<40_000||body.length>200_000)invalid();return body;}
export async function fetchKofpiBundle(fetcher:typeof fetch=fetch){const signal=AbortSignal.timeout(20_000),list=await read(fetcher,kofpiSource.url,signal),details=await Promise.all(expected.map(async x=>({id:x.id,html:await read(fetcher,base+x.id,signal)})));return JSON.stringify({list,details});}
function listRows(html:string){const clean=html.replace(/<!--[\s\S]*?-->/g,'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');const rows=[...clean.matchAll(/<tr>\s*<td>(\d+)<\/td>\s*<td class="title">\s*<a[^>]*onclick="fnGoView\('(\d+)'\); return false;"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<td>[^<]*<\/td>\s*<td>(\d{4}-\d{2}-\d{2})<\/td>\s*<\/tr>/g)].map(x=>({no:x[1],id:x[2],title:plain(x[3].replace(/<span class="badge[^"]*">[\s\S]*?<\/span>/g,'')),posted:x[4]}));if(rows.length!==10||new Set(rows.map(x=>x.id)).size!==10)invalid();return rows;}
export function collectKofpiBundle(input:string,knownIds:string[]=[],now=new Date()){
  let data:{list?:unknown;details?:unknown};try{data=JSON.parse(input);}catch{invalid();}if(typeof data.list!=='string'||!Array.isArray(data.details)||data.details.length!==2)invalid();const rows=listRows(data.list),known=new Set(knownIds),seen=new Set<string>();
  const items=(data.details as Array<Record<string,unknown>>).flatMap<KofpiItem>(detail=>{if(typeof detail.id!=='string'||typeof detail.html!=='string'||seen.has(detail.id))invalid();seen.add(detail.id);const e=expected.find(x=>x.id===detail.id),row=rows.find(x=>x.id===detail.id);if(!e||!row||row.title!==e.title||row.posted!==e.posted)invalid();const html=detail.html,title=plain(html.match(/<tr class="title">[\s\S]*?<h3>([\s\S]*?)<\/h3>/)?.[1]||''),posted=plain(html.match(/<strong>작성일<\/strong>\s*([^<]+)/)?.[1]||''),body=plain(html.match(/<td colspan="4" class="view_cont">([\s\S]*?)<\/td>/)?.[1]||'');if(title!==e.title||posted!==e.posted)invalid();
    if(e.id==='12609'){
      for(const fact of ['한국임업진흥원 공고 제2026-50호','임업인 및 기업','5개사 내외','1개사 당 8백만원 이내','전문가 자문','한국임업진흥원이 직접 집행','2026. 8. 24.(월) ~ 12. 31.(금)','예산 소진 시 접수가 조기 마감','전자우편 또는 방문·우편 접수'])if(!body.includes(fact))invalid();
      if(now>=new Date('2027-01-01T00:00:00+09:00')&&!known.has(e.id))return [];
      return [{sourceId:kofpiSource.id,externalId:e.id,institution:'한국임업진흥원',group:'공사·공단',title:e.title,category:'시제품·사업화 지원',audience:'산양삼 등 산촌자원 시제품 개발 희망자 · 임업인, 임산물 생산자단체·가공기업 등 우선',region:null,sourceName:kofpiSource.name,sourceUrl:base+e.id,announcedFrom:e.posted,applicationFrom:'2026-08-24',applicationTo:'2026-12-31',opensAt:null,closesAt:null,deadlineLabel:'2026-12-31까지 · 예산 소진 시 조기 마감',status:now>=new Date('2027-01-01T00:00:00+09:00')?'closed':'unknown',ministry:'산림청',supportBudget:8_000_000,applicationMethod:'전자우편 또는 함양 산양삼특화산업진흥센터 방문·우편 접수 · 사전 연락'}];
    }
    for(const fact of ['임산물 오프라인 판로 확보','사업자등록이 완료된 자','판매 및 전시공간 셋팅 지원','18개사 내외','2026. 8. 27.(목) ~ 2026. 9. 11','18:00까지','전자우편으로 제출서류 접수'])if(!body.includes(fact))invalid();const closesAt=new Date('2026-09-11T18:00:00+09:00'),ended=now>closesAt;if(ended&&!known.has(e.id))return [];
    return [{sourceId:kofpiSource.id,externalId:e.id,institution:'한국임업진흥원',group:'공사·공단',title:e.title,category:'판로·전시 지원',audience:'임산물 원물·가공품을 생산하며 사업자등록을 완료한 자 · 공고문 세부요건 확인',region:'서울',sourceName:kofpiSource.name,sourceUrl:base+e.id,announcedFrom:e.posted,applicationFrom:'2026-08-27',applicationTo:'2026-09-11',opensAt:new Date('2026-08-27T00:00:00+09:00'),closesAt,deadlineLabel:'2026-09-11 18:00',status:ended?'closed':now<new Date('2026-08-27T00:00:00+09:00')?'upcoming':'open',ministry:'산림청',applicationMethod:'전자우편으로 공고문 제출서류 접수'}];
  });if(seen.size!==2)invalid();return {items,parsedRows:rows.length,parsedDetails:seen.size};
}
