export const koicaSource={id:'koica-youth-contest',institutionId:'public-288',name:'외교부·KOICA 국제개발협력 청년공모전',url:'https://www.worldfriendskorea.or.kr/kor/info/noticeList.do'};
const detailUrl='https://www.worldfriendskorea.or.kr/kor/info/noticeDetail.do?noticeNo=48';
function invalid():never{throw new Error('KOICA 국제개발협력 청년공모전 구조 확인 필요');}
function plain(value:string){return value.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):parseInt(n,10))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
async function read(fetcher:typeof fetch,url:string,signal:AbortSignal){const response=await fetcher(url,{redirect:'manual',signal,headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'}});if(!response.ok)throw new Error(`KOICA youth contest HTTP ${response.status}`);const body=await response.text();if(body.length<35_000||body.length>150_000)invalid();return body;}
export async function fetchKoicaBundle(fetcher:typeof fetch=fetch){const signal=AbortSignal.timeout(20_000);const [list,detail]=await Promise.all([read(fetcher,koicaSource.url,signal),read(fetcher,detailUrl,signal)]);return JSON.stringify({list,detail});}
export function collectKoicaBundle(input:string,knownIds:string[]=[],now=new Date()){
  let data:{list?:unknown;detail?:unknown};try{data=JSON.parse(input);}catch{invalid();}if(typeof data.list!=='string'||typeof data.detail!=='string')invalid();
  const rows=[...data.list.matchAll(/<a[^>]*onclick="fnDetail\('(\d+)'\)"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<p[^>]*class="date"[^>]*>(\d{4}-\d{2}-\d{2})<\/p>/gi)].map(x=>({id:x[1],title:plain(x[2]),posted:x[3]}));if(rows.length<8||rows.length>20||new Set(rows.map(x=>x.id)).size!==rows.length)invalid();
  const id='48',expectedTitle='📢 2026년 국제개발협력 청년 공모전 개최!(~9/30)',row=rows.find(x=>x.id===id);if(!row||row.title!==expectedTitle||row.posted!=='2026-09-02')invalid();
  const title=plain(data.detail.match(/<p[^>]*class="tit"[^>]*>([\s\S]*?)<\/p>/i)?.[1]||''),posted=plain(data.detail.match(/<p[^>]*class="tit"[^>]*>[\s\S]*?<\/p>[\s\S]*?<li>\s*(\d{4}-\d{2}-\d{2})\s*<\/li>/i)?.[1]||''),body=plain(data.detail);if(title!==expectedTitle||posted!==row.posted||!data.detail.includes(`noticeNo=${id}`))invalid();
  for(const fact of ['청년의 경험과 아이디어','청년들의 KOICA 사업 참여','청년들의 참여 강화 방안','2026. 8. 27.','9. 30.','18:00','A4','10페이지 이내','PDF 파일로 제출','대상: 150만 원 상당','외교부장관상','KOICA 이사장상','공모전 홈페이지','https://mofa2.spectory.net/mofa2'])if(!body.includes(fact))invalid();
  const end=new Date('2026-09-30T18:00:00+09:00'),ended=now>end;if(ended&&!knownIds.includes(id))return {items:[],parsedRows:rows.length,parsedDetails:1};
  return {items:[{sourceId:koicaSource.id,externalId:id,institution:'한국국제협력단',group:'공사·공단',title:'2026년 국제개발협력 청년공모전',category:'정책·아이디어 공모전',audience:'국제개발협력 경험 또는 청년 참여 확대 아이디어를 제출하려는 청년 · 세부 자격은 공모전 홈페이지 확인',region:null,sourceName:koicaSource.name,sourceUrl:detailUrl,announcedFrom:'2026-09-02',applicationFrom:'2026-08-27',applicationTo:'2026-09-30',opensAt:new Date('2026-08-27T00:00:00+09:00'),closesAt:end,deadlineLabel:'2026-09-30 18:00',status:ended?'closed':now<new Date('2026-08-27T00:00:00+09:00')?'upcoming':'open',ministry:'외교부',applicationMethod:'A4 10쪽 이내 원고를 PDF로 작성해 공식 공모전 홈페이지에서 제출'}],parsedRows:rows.length,parsedDetails:1};
}
