export const koipaPatentSource={id:'koipa-patent',institutionId:'public-308',name:'한국지식재산보호원 특허분쟁 대응전략',url:'https://www.koipa.re.kr/home/board/brdDetail.do?menu_cd=000041&num=7024'};
const configs=[
  {id:'7024',file:'6316',title:'[정기 7차] 2026년 특허분쟁 대응전략 지원사업',region:null,audience:'해외기업과 특허 또는 영업비밀 분쟁·위험이 있는 국내 중소·중견기업, 공동대응 협의체 및 유형별 대학·공공연',bytes:593885,magic:'%PDF-1.7',end:'0\n%%EOF\n',hash:'aa62c32bea25b6e590324ca1b127a1e8f7b6b22d6f9663b611a8f02f511721fa'},
  {id:'7025',file:'6318',title:'[인천연계_정기 7차] 2026년 특허분쟁 대응전략 지원사업',region:'인천',audience:'인천 미추홀구·연수구·남동구·부평구·서구 소재의 해외 특허분쟁·위험이 있는 중소기업(개인사업자 포함)',bytes:293489,magic:'%PDF-1.6',end:'7\r\n%%EOF',hash:'cb5d1523d4de0c3cd4cb0c87ed3119d528044029e9845d165e8d6dacb2939681'},
  {id:'7026',file:'6320',title:'[충남연계_정기 7차] 2026년 특허분쟁 대응전략 지원사업',region:'충남',audience:'충청남도 소재의 해외 특허분쟁·위험이 있는 중소기업(개인사업자 포함)',bytes:291179,magic:'%PDF-1.6',end:'7\r\n%%EOF',hash:'c9ca20fb03ee9fc46762bdf1a309bfa453cb523494220b5948db097d6b09d2bc'},
] as const;
const detailUrl=(id:string)=>`https://www.koipa.re.kr/home/board/brdDetail.do?menu_cd=000041&num=${id}`;const pdfUrl=(id:string)=>`https://www.koipa.re.kr/home/board/fileDownload/${id}.do`;
function invalid():never{throw new Error('한국지식재산보호원 특허분쟁 공고 구조 확인 필요');}function plain(v:string){return v.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();}async function hash(b:ArrayBuffer){const d=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('');}
export async function fetchKoipaPatentBundle(fetcher:typeof fetch=fetch){const headers={accept:'text/html,application/pdf','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'};const rows=await Promise.all(configs.map(async c=>{const [dr,pr]=await Promise.all([fetcher(detailUrl(c.id),{headers,redirect:'manual',signal:AbortSignal.timeout(20_000)}),fetcher(pdfUrl(c.file),{headers,redirect:'manual',signal:AbortSignal.timeout(20_000)})]);if(!dr.ok||!pr.ok)throw new Error(`KOIPA patent ${c.id} HTTP ${dr.status}/${pr.status}`);const html=await dr.text(),b=await pr.arrayBuffer(),v=new Uint8Array(b),hb=new TextEncoder().encode(html).length;if(hb<100_000||hb>250_000||v.length<250_000||v.length>700_000)invalid();return {html,pdfBytes:v.length,pdfMagic:new TextDecoder().decode(v.slice(0,8)),pdfEnd:new TextDecoder().decode(v.slice(-8)),pdfHash:await hash(b)};}));return JSON.stringify({rows});}
export function collectKoipaPatentBundle(input:string,knownIds:string[]=[],now=new Date()){let d:{rows?:unknown};try{d=JSON.parse(input);}catch{invalid();}if(!Array.isArray(d.rows)||d.rows.length!==3)invalid();const end=Date.parse('2026-09-21T18:00:00+09:00');const items=configs.flatMap((c,i)=>{const r=(d.rows as Record<string,unknown>[])[i];if(typeof r?.html!=='string'||r.pdfBytes!==c.bytes||r.pdfMagic!==c.magic||r.pdfEnd!==c.end||r.pdfHash!==c.hash)invalid();const t=plain(r.html);if(!t.includes(c.title)||!t.includes('2026-09-01')||!r.html.includes(`fileDown('${c.file}')`)&&!r.html.includes(`fileDown(${c.file})`))invalid();if(now.getTime()>end&&!knownIds.includes(c.id))return [];return [{sourceId:koipaPatentSource.id,externalId:c.id,institution:'한국지식재산보호원',group:'공사·공단',title:c.title,category:'해외 특허분쟁 대응전략',audience:c.audience,region:c.region,sourceName:koipaPatentSource.name,sourceUrl:detailUrl(c.id),announcedFrom:'2026-09-01',applicationFrom:'2026-09-01',applicationTo:'2026-09-21',opensAt:new Date('2026-09-01T00:00:00+09:00'),closesAt:new Date('2026-09-21T18:00:00+09:00'),deadlineLabel:'2026-09-21 18:00까지',status:now.getTime()>end?'closed':'open',ministry:'지식재산처',supportBudget:null,applicationMethod:'IP-NAVI 지재권분쟁 대응전략 지원사업 관리시스템에서 신청서와 구비서류 온라인 제출'}];});return {parsedPages:6,items};}
