export const koreahanaSource={id:'koreahana-opportunities',institutionId:'public-306',name:'남북하나재단 모집공고',url:'https://www.koreahana.or.kr/home/kor/board.do?menuPos=52'};
const detail=(id:string)=>`https://www.koreahana.or.kr/home/kor/board.do?act=detail&idx=${id}&menuPos=52`;
const expected=[{id:'20469',title:'2026년도 하반기 남북하나재단 장학생 선발 공고(~9.21)'},{id:'20465',title:'2026년 창업디딤돌센터 9월 (예비)창업가 창업교육 참여자 모집공고(~9.18)'}] as const;
function invalid():never{throw new Error('남북하나재단 모집공고 구조 확인 필요');}
function plain(value:string){return value.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):parseInt(n,10))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
async function read(fetcher:typeof fetch,url:string,signal:AbortSignal){const response=await fetcher(url,{redirect:'manual',signal,headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'}});if(!response.ok)throw new Error(`Koreahana opportunities HTTP ${response.status}`);const body=await response.text();if(body.length<150_000||body.length>500_000)invalid();return body;}
export async function fetchKoreahanaBundle(fetcher:typeof fetch=fetch){const signal=AbortSignal.timeout(20_000);const [list,...details]=await Promise.all([read(fetcher,koreahanaSource.url,signal),...expected.map(x=>read(fetcher,detail(x.id),signal))]);return JSON.stringify({list,details:details.map((html,i)=>({id:expected[i].id,html}))});}
export function collectKoreahanaBundle(input:string,knownIds:string[]=[],now=new Date()){let data:{list?:unknown;details?:unknown};try{data=JSON.parse(input);}catch{invalid();}if(typeof data.list!=='string'||!Array.isArray(data.details)||data.details.length!==2)invalid();
  const rows=[...data.list.matchAll(/fn_edit\('detail',\s*'(\d+)',\s*'[A-Z]'\)[\s\S]*?<\/tr>/gi)].map(x=>({id:x[1],text:plain(x[0])}));if(rows.length<2||rows.length>60)invalid();const unique=new Map(rows.map(x=>[x.id,x]));for(const e of expected){const row=unique.get(e.id);if(!row||!row.text.includes(e.title)||!row.text.includes(e.id==='20469'?'2026-09-04':'2026-09-01'))invalid();}
  const pages=new Map<string,string>();for(const value of data.details){if(!value||typeof value!=='object')invalid();const id=(value as {id?:unknown}).id,html=(value as {html?:unknown}).html;if(typeof id!=='string'||typeof html!=='string'||pages.has(id))invalid();pages.set(id,plain(html));}for(const e of expected)if(!pages.get(e.id)?.includes(e.title))invalid();
  const scholarship=pages.get('20469')!;for(const fact of ['북한이탈주민지원재단 공고 제2026','98호','접수기간 : 9. 4','9. 21.','18:00','재단 온라인 신청시스템','장학금 지원','우편접수 불가','부모 명의 신청불가'])if(!scholarship.includes(fact))invalid();
  const startup=pages.get('20465')!;for(const fact of ['북한이탈주민지원재단 공고 제2026-97호','창업에 관심이 있는 북향민','20명 이내','대중교통비 지원','2026년 9월 18일','17시까지','didim@nkrf.or.kr','방문 또는 우편접수'])if(!startup.includes(fact))invalid();
  const specs=[{id:'20469',end:new Date('2026-09-21T18:00:00+09:00'),item:{title:'2026년도 하반기 남북하나재단 장학생 선발',category:'장학금·교육지원',audience:'북향민 대학원생·대학생·고등학생·검정고시 합격자 및 요건을 충족한 북향민 자녀',applicationFrom:'2026-09-04',applicationTo:'2026-09-21',opensAt:new Date('2026-09-04T00:00:00+09:00'),deadlineLabel:'2026-09-21 18:00',applicationMethod:'신청자 본인 명의로 재단 온라인 신청시스템에서 장학금 지원 신청 · 우편 및 부모 명의 신청 불가'}},{id:'20465',end:new Date('2026-09-18T17:00:00+09:00'),item:{title:'2026년 창업디딤돌센터 9월 예비창업가 창업교육',category:'창업교육·역량강화',audience:'창업에 관심 있는 북향민 20명 이내 · 해당 AI 교육 프로그램 기참여자 제외',applicationFrom:null,applicationTo:'2026-09-18',opensAt:null,deadlineLabel:'2026-09-18 17:00',applicationMethod:'신청서와 개인정보동의서를 이메일, 방문 또는 우편으로 제출'}}] as const;
  const items=specs.flatMap(s=>{const ended=now>s.end;if(ended&&!knownIds.includes(s.id))return [];return [{sourceId:koreahanaSource.id,externalId:s.id,institution:'북한이탈주민지원재단',group:'공사·공단',...s.item,region:null,sourceName:koreahanaSource.name,sourceUrl:detail(s.id),announcedFrom:s.id==='20469'?'2026-09-04':'2026-09-01',closesAt:s.end,status:ended?'closed':s.item.opensAt&&now<s.item.opensAt?'upcoming':'open',ministry:'통일부',supportBudget:null}];});return {items,parsedRows:unique.size,parsedDetails:2};
}
