export const kywaSource={id:'kywa-opportunities',institutionId:'public-284',name:'한국청소년활동진흥원 공모·지원사업',url:'https://www.kywa.or.kr/pressinfo/notice_list.jsp'};
const base='https://www.kywa.or.kr/pressinfo/notice_view.jsp?no=';
type KywaItem={sourceId:string;externalId:string;institution:string;group:string;title:string;category:string;audience:string;region:string|null;sourceName:string;sourceUrl:string;announcedFrom:string;applicationFrom:string|null;applicationTo:string|null;opensAt:Date|null;closesAt:Date|null;deadlineLabel:string;status:string;ministry:string;supportBudget?:number|null;applicationMethod:string};
const expected=[
  {id:'36728',title:'2026년 청소년포상제 우수사례 공모전 공고(~10.6.)',posted:'2026-09-03'},
  {id:'36727',title:'2026년 수련시설 재난·안전보건관리체계 구축 지원사업 참여시설 모집 안내',posted:'2026-09-02'},
  {id:'36721',title:'2026년 청소년활동 안전캠페인 PLAY SAFE 숏폼 챌린지 공모전 운영 안내',posted:'2026-09-01'},
  {id:'36719',title:'역량기반 청소년활동 인증 운영기관 지원사업 안내',posted:'2026-08-31'},
  {id:'36701',title:'2026년 우수 청소년활동 프로그램 지원사업 보급활동(실전형) 참여기관 추가 모집',posted:'2026-08-25'},
  {id:'36597',title:'2026년 청소년자원봉사활동 우수사례 공모전 공고',posted:'2026-07-30'},
] as const;
function invalid():never{throw new Error('한국청소년활동진흥원 공모·지원사업 구조 확인 필요');}
function plain(value:string){return value.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):parseInt(n,10))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
async function read(fetcher:typeof fetch,url:string,signal:AbortSignal){const response=await fetcher(url,{redirect:'manual',signal,headers:{accept:'text/html','user-agent':'GongmoaSourceMonitor/1.1 (+https://gongmoa.uflufl.chatgpt.site)'}});if(!response.ok)throw new Error(`KYWA ${new URL(url).searchParams.get('no')||'list'} HTTP ${response.status}`);const bytes=await response.arrayBuffer();if(bytes.byteLength<35_000||bytes.byteLength>250_000)invalid();return new TextDecoder('euc-kr').decode(bytes);}
export async function fetchKywaBundle(fetcher:typeof fetch=fetch){const signal=AbortSignal.timeout(20_000),list=await read(fetcher,kywaSource.url,signal),details=await Promise.all(expected.map(async x=>({id:x.id,html:await read(fetcher,base+x.id,signal)})));return JSON.stringify({list,details});}
function rowsOf(html:string){const rows=[...html.matchAll(/<tr[^>]*>[\s\S]*?<td[^>]*>(?:<span[^>]*>공지<\/span>|\d+)<\/td>[\s\S]*?<td[^>]*class="table-l-t"[^>]*>[\s\S]*?<a[^>]+href="(?:\.\.\/pressinfo\/)?notice_view\.jsp\?[^"']*no=(\d+)[^"']*"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<td[^>]*>[^<]*<\/td>[\s\S]*?<td[^>]*>(\d{4}-\d{2}-\d{2})<\/td>[\s\S]*?<\/tr>/gi)].map(x=>({id:x[1],title:plain(x[2]),posted:x[3]}));const unique=[...new Map(rows.map(x=>[x.id,x])).values()];if(unique.length<10||unique.length>40)invalid();return unique;}
const openDate=(from:string,now:Date)=>now<new Date(`${from}T00:00:00+09:00`)?'upcoming':'open';
export function collectKywaBundle(input:string,knownIds:string[]=[],now=new Date()){
  let data:{list?:unknown;details?:unknown};try{data=JSON.parse(input);}catch{invalid();}if(typeof data.list!=='string'||!Array.isArray(data.details)||data.details.length!==expected.length)invalid();const rows=rowsOf(data.list),known=new Set(knownIds),seen=new Set<string>();
  const items=(data.details as Array<Record<string,unknown>>).flatMap<KywaItem>(detail=>{if(typeof detail.id!=='string'||typeof detail.html!=='string'||seen.has(detail.id))invalid();seen.add(detail.id);const e=expected.find(x=>x.id===detail.id),row=rows.find(x=>x.id===detail.id);if(!e||!row||row.title!==e.title||row.posted!==e.posted)invalid();const html=detail.html,title=plain(html.match(/<h4>([\s\S]*?)<\/h4>/)?.[1]||''),posted=plain(html.match(/작성일\s*:\s*<span>([^<]+)<\/span>/)?.[1]||''),body=plain(html.match(/<div[^>]+class="[^"']*view-con[^"']*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]||html.slice(html.indexOf('<h4>')));if(title!==e.title||posted!==e.posted)invalid();const common={sourceId:kywaSource.id,externalId:e.id,institution:'한국청소년활동진흥원',group:'공사·공단',title:e.title,region:null,sourceName:kywaSource.name,sourceUrl:base+e.id,announcedFrom:e.posted,ministry:'성평등가족부'};
    if(e.id==='36727'){for(const fact of ['청소년수련시설','약 30개소 선정','온라인 교육','현장 방문','2026. 9. 2.','9. 11.','18:00까지'])if(!body.includes(fact))invalid();const end=new Date('2026-09-11T18:00:00+09:00'),ended=now>end;if(ended&&!known.has(e.id))return [];return [{...common,category:'시설 안전·컨설팅 지원',audience:'청소년수련시설',applicationFrom:'2026-09-02',applicationTo:'2026-09-11',opensAt:new Date('2026-09-02T00:00:00+09:00'),closesAt:end,deadlineLabel:'2026-09-11 18:00',status:ended?'closed':openDate('2026-09-02',now),applicationMethod:'공고 본문의 온라인 신청서 제출'}];}
    if(e.id==='36701'){for(const fact of ['청소년수련시설 및 단체 등 청소년관련기관','운영 매뉴얼 무상 제공','맞춤형 컨설팅','100,000원','모집완료 시 까지','program@kywa.or.kr'])if(!body.includes(fact))invalid();return [{...common,category:'프로그램 보급·운영 지원',audience:'청소년수련시설·단체 등 청소년 관련기관',applicationFrom:'2026-08-25',applicationTo:null,opensAt:new Date('2026-08-25T00:00:00+09:00'),closesAt:null,deadlineLabel:'모집 완료 시까지 · 일부 프로그램 조기 마감 가능',status:'unknown',supportBudget:100_000,applicationMethod:'신청서 작성 후 program@kywa.or.kr 이메일 제출'}];}
    if(e.id==='36719'){for(const fact of ['역량기반 청소년활동 인증 프로그램 보유기관 60개소','기관당 30만원 한도','동반성장몰','신청서'])if(!body.includes(fact))invalid();return [{...common,category:'활동장비·소모품 지원',audience:'역량기반 청소년활동 인증 프로그램 보유기관',applicationFrom:null,applicationTo:null,opensAt:null,closesAt:null,deadlineLabel:'신청기간 원문 확인',status:'unknown',supportBudget:300_000,applicationMethod:'동반성장몰 상품 확인 후 신청서를 진흥원 담당자에게 제출'}];}
    if(e.id==='36721'){for(const fact of ['청소년과 국민','2026. 9.1.','10.5.','총 상금 200만원','SNS','신청'])if(!body.includes(fact))invalid();const after=now>=new Date('2026-10-06T00:00:00+09:00');if(after&&!known.has(e.id))return [];return [{...common,category:'콘텐츠 공모전',audience:'청소년 및 청소년을 포함한 가족 등 국민 개인·팀',applicationFrom:'2026-09-01',applicationTo:'2026-10-05',opensAt:new Date('2026-09-01T00:00:00+09:00'),closesAt:null,deadlineLabel:'2026-10-05까지 · 마감시각 미표기',status:after?'closed':openDate('2026-09-01',now),supportBudget:2_000_000,applicationMethod:'SNS 릴스·숏츠 게시 후 공모전 페이지에서 신청'}];}
    if(e.id==='36728'){for(const fact of ['2026년 청소년포상제 참여 청소년','지도자','운영기구','총 45점','award@kywa.or.kr','2025. 9.9.','10. 6.'])if(!body.includes(fact))invalid();const after=now>=new Date('2026-10-07T00:00:00+09:00');if(after&&!known.has(e.id))return [];return [{...common,category:'우수사례 공모전',audience:'2026년 청소년포상제 참여 청소년·지도자·운영기구',applicationFrom:null,applicationTo:'2026-10-06',opensAt:null,closesAt:null,deadlineLabel:'10월 6일까지 · 본문 시작연도 불일치로 원문 확인',status:after?'closed':'unknown',applicationMethod:'신청서와 활동수기 또는 성과요약서를 award@kywa.or.kr로 제출'}];}
    for(const fact of ['봉사활동 참여 청소년','지도자, 기관','2026. 8. 3.','10. 23.','18:00까지','dovol@kywa.or.kr','총 21점'])if(!body.includes(fact))invalid();const end=new Date('2026-10-23T18:00:00+09:00'),ended=now>end;if(ended&&!known.has(e.id))return [];return [{...common,category:'우수사례 공모전',audience:'청소년자원봉사 참여 청소년(팀)·지도자·운영기관',applicationFrom:'2026-08-03',applicationTo:'2026-10-23',opensAt:new Date('2026-08-03T00:00:00+09:00'),closesAt:end,deadlineLabel:'2026-10-23 18:00',status:ended?'closed':openDate('2026-08-03',now),applicationMethod:'부문별 제출서류를 dovol@kywa.or.kr로 이메일 접수'}];
  });if(seen.size!==expected.length)invalid();return {items,parsedRows:rows.length,parsedDetails:seen.size};
}
